### ISSUE TITLE
Low CPU usage

### ISSUE THREAD

**Issue by kjmaurice** [soedinglab/hh-suite#103]
I am running hhblits 3.0.3 against the uniclust30 database.  The CPU usage is low.  It spends much of it's time at around 2% with basically nothing else running.  Is this a problem with memory or reading from the hard drive?  Is there a way to speed it up?  My computer has 8 gb ram and the DB is on the internal hard drive.

**Comment by martin-steinegger** [comment]
The database has to fit into the memory to best fast. If the database does not fit than HHblits will make many random IO calls, which is super slow. You can touch the database in memory using https://github.com/hoytech/vmtouch

**Comment by wrmartin** [comment]
I know this was closed a few years ago, but I'm having the same issue intermittently.  There are times where hhblits (latest version) will max out 32 threads, and other times where it sits at a few percent on a single thread.  My workstation has 256gb of ram, but I don't believe that to be an issue since the problem is intermittent.  Nothing else is running on the workstation along with hhblits.

**Comment by milot-mirdita** [comment]
Are you using `hhblits` or `hhblits_omp`?

Git HH-suite has some performance fixes for `hhblits_omp` that we have encountered and solved on our dual epyc machine. However, performance is still not great on the 256-core machine. 

I don't know of any performance issues with the `hhblits` binary. If the database is searched from a slow hard disk, it might get stuck on IO.

**Comment by wrmartin** [comment]
I am using hhblits (from bioconda).  It's odd because it's not every time I run.  I'm also running against uniclust30 (alphafold workflow).  One of my workstations I have not been able to get above 4% CPU usage, while the other *usually* will use 32 threads (of 64, but I'm only passing 32), but after rebooting a half hour ago my first run would not go over 14% utilization.  I know it's a difficult case when it's intermittent.

**Comment by milot-mirdita** [comment]
How do you store the database? Especially the uniclust_cs219.ffdata/index need to be on as fast a disk as possible (RAM disk if possible).

**Comment by wrmartin** [comment]
It is on a regular 7200rpm hard disk.

**Comment by milot-mirdita** [comment]
I guess HHblits is mostly stuck waiting for the HDD.
You can try a similar procedure as described here:
https://github.com/soedinglab/hh-suite/issues/281#issuecomment-888689484

**Comment by wrmartin** [comment]
It appears disk I/O may be the issue.  Moving uniclust30 to the SSD allowed all threads to run, but when it started on BFD (which I can't fit on the SSD) it ran with ~15% of a single thread.  Can't sort why it has worked fine before though.  Thanks.

**Comment by milot-mirdita** [comment]
You can probably still do what I explained in the linked comment, if you move only the bfd cs219 database files to the SSD  and leave the others where they were, you should still see a big speed-up.
