### ISSUE TITLE
addss.pl discards first sequence in input a3m file

### ISSUE THREAD

**Issue by aschafu** [soedinglab/hh-suite#169]
##  Expected Behavior
When one runs addss.pl on a an alignment in a3m format, the first sequence should be taken as the reference sequence for the pdb structure.

## Current Behavior
The first sequence gets discarded, a consensus sequence is built and then the dssp information is often discarded if the consensus is too different from the first sequence.

## Steps to Reproduce (for bugs)
* Generate an a3m file with hhblits, e.g. `hhblits -i pdbSeq.fas -d uniclust30 -oa3m pdbSeq.a3m`
* Run addss.pl, e.g. `addss.pl -i pdbSeq.a3m -o pdbSeq_withSS.a3m`
e.g. sequence 6nbo_A produces the error:
```
>6nbo_A
MAHHHHHHMTALLIRNVRTGADDALDILIEGDRIARTGPSLDAPPGCAIEEGAGAIALPGLVEGHTHLDKTHWGMPWYRNAVGPRLVDRIENERHYRATSGHDAGAASLALARAFLAAGTTRIRTHVDVDTDAGLRHLHRVLDTRETLRGQVEIQIVAFPQSGVLKRPGTDALLADALAAGADLLGGLDPCAIEGDPVKAVDVLFGIAERYGRGLDLHLHERGSMGAYSLDLILQRTAALGMQHKVTISHAFCLGDLAERERDALLARMAELGVAVVTTAPAAVPVPSVLACRAAGVTVIGGNDGVRDTWTPYGSPDMLERAMLIAMRNDFRRDDALEVALECVTHGAARGCGFDAYGLQPGARADVVLVDAMTLAEAVVARPVRRLVVSSGKIVARNGALV
```

## HH-suite Output (for bugs)
```
WARNING: in 6nbo_A: alignment score with dssp residues too low: Score/len=0.296203.

IN:    MAHHHHHHMTALLLVDVYTGIIENGDILIEDGRIAAIGPSSEIPPG------AEVIDASGKIVLPGLIDAHTHLDQSGLRGPWYR---G-RIGPSFE-EWLSSMRAYRALDPEDLYAAALRGAREALRSGVTTVRDMGDPGPDAGLRAL-------EAAIAAGSGIRGVVDYGIFGFPPEGLFERDGAEELVRELLAAGADVIKGFSPHSPPSCSPEELRAIVELARELGLP-----VHIHAAESEAEGEFSLEEIIER--------LIEAG------LDP---R---------VIIEHCSHLSDLDDEEAE-EDIELLA---ERGVSVV---PCPHSNSGIPPLRELLEAGVPV-------ALG--------------TDSPASPFNPNGSPDMLEEMRLAALR-------AGLSPRLSPEEALRMATINGAR-----ALGLDIGSIEPGKDADLVVLDGDPLEDIPYL------RPVSRLVIVDGRVVYRDGKLV
MATCH: ........MTALL...V.TG.....DILIE..RIA..GPS...PPG......A......G.I.LPGL...HTHLD......PWYR...G.RI....E.E.....R.YRA....D..AA.L..AR..L..G.T..R...D...DAGLR.L.......E.........RG.V...I..FP..G...R.G...L....LAAGAD...G..P.....C......AI.....E.G.P.....V..............L..I.ER........L.E.G......LD....R.........V.I.H...L.DL....AE.E...LLA...E.GV.VV...P................A.VPV.......A.G..............T........P.GSPDMLE...L.A.R.......A.....L..E.AL...T...AR.....A.GL......PG..AD.VVL......D...L......RPV.RLV...G..V.R.G.LV
DSSP:  --------MTALLIRNVRTGADDALDILIEGDRIARTGPSLDAPPGCAIEEGA------GAIALPGLVEGHTHLDKTHWGMPWYRNAVGDRI----ENE-----RHYRATSGHDAGAASLALARAFLAAGTTRIRTHVDVDTDAGLRHLHRVLDTRETL-------RGQVEIQIVAFPQSGVLKRPGTDALLADALAAGADLLGGLDP-----C------AI-----E-GDPVKAVDV--------------LFGIAERYGRGLDLHLHERGSMGAYSLDLILQRTAALGMQHKVTISHAFCLGDL----AERERDALLARMAELGVAVVTTAP----------------AAVPVPSVLACRAAGVTVIGGNDGVRDTWT--------PYGSPDMLERAMLIAMRNDFRRDDA-----L--EVALECVTHGAARGCGFDAYGLQ-----PGARAD-VVLV-----DAMTLAEAVVARPVRRLVVSSGKIVARNGALV
```

## Your Environment
* checked out from git (1f8107689c398e683d2d4d72352a91a584454679)

## Workaround
The problem seems to occur because addss.pl expects there to be a header line. So, if you add an artificial header, the first sequence does not get discarded and the secondary structure gets added.

**Comment by Alexamk** [comment]
Hi. I ran into a similar problem. The issue arose for me when making custom HHPred databases with added secondary structure. The addss.pl did not work for a small fraction of the sequences (~5%).
The offending lines seem to be lines 194-195 in the addss.pl script, which wrongly add the first sequence to the header instead of to the sequences, in the case where there is no header. 
This results in the second sequence being used as if it was the original query sequence. However, this sequence may be filtered out of the alignment file in the follwing hhfilter step. 
This would then break blastpgp later on, as this relies on the original query sequence being present in the a3m file. 

The workaround I used was to add an extra condition to line 194, as below:
`while ($header =~ />$/ && $header !~ /\n>$/ && $header ne ">") {`

This seems to work so far, but I haven't thoroughly tested it yet.
