### ISSUE TITLE
Problem running HHSearch on Debian Testing

### ISSUE THREAD

**Issue by zclandry** [soedinglab/hh-suite#48]
I am unable to run HHSearch anymore.  I am not sure when it stopped working. I am running Debian Testing, and installed hhsuite from the repository.  The following is a trace:

hhsearch -i HHSearch.hhm -d HHSearch2.hhm 
- 17:20:44.102 INFO: Search results will be written to HHSearch.hhr!

- 17:20:44.102 ERROR: In /build/hhsuite-3.0~beta2+dfsg/src/hhdatabase.cpp:35: FFindexDatabase:

- 17:20:44.102 ERROR: 	could not open file 'HHSearch2.hhm_cs219.ffdata'

**Comment by milot-mirdita** [comment]
Hi zclandry,

Your issue should hopefully be solved after Markus reviews and merges my fix.

When the fix is merged, please make sure your hhm database is named like this:
`HHSearch2_hhm.ffdata` and `HHSearch2_hhm.ffindex`

and you call hhsearch without the `_hhm` suffix:
`hhsearch -i HHSearch.hhm -d HHSearch2`

Best regards,
Milot
