### ISSUE TITLE
Handling all of Uniprot -- including titin

### ISSUE THREAD

**Issue by aschafu** [soedinglab/hh-suite#71]
This is more a question than a bug report:
In the settings of hhblits (in  src/hhdecl.cpp) which you distribute the parameters determining maximum sequence length are set  to
```
        maxcol = 32765; // max number of columns in sequence/MSA input files; must be <= LINELEN and >= maxres
        maxres = 20001;           // max number of states in HMM; must be <= LINELEN

```
This is shorter than the current longest sequence in Uniprot (36991:  A0A1V4K6M4 -- see
http://www.ebi.ac.uk/uniprot/TrEMBLstats).  Since your limit 32765 and e.g. 36991 are not so far apart, I was wondering why you don't choose a higher limit that covers all of Uniprot.

Thanks!

**Comment by aschafu** [comment]
Hm, maybe this is turning into a bug report, after all:
I'm experimenting with increasing the maxcol / maxres values to (3900/3001) and then running titin (sp|Q8WZ42|TITIN_HUMAN). Now I just noticed one alignment with very astonishing values:

```
No 34
>tr|A8WH16|A8WH16_XENTR Mybpc2 protein (Fragment) OS=Xenopus tropicalis GN=mybpc2 PE=2 SV=1
Probab=100.00  E-value=1.7e-90  Score=927.59  Aligned_cols=1  Identities=0%  Similarity=0.000  Sum_probs=0.0  Template_Neff=2.026

```
(the alignment itself is empty). 
Any ideas? -- I suspect that this because maxres is still smaller than the sequence length?

**Comment by milot-mirdita** [comment]
Hi Andrea,
I am trying to reproduce the issue. What database did you use to search against? Is there any reason you chose 30001 (I assume you were missing one zero)? I tried it with a larger value and there I don't see any empty alignments.

One thing that might be wrong is that maxcol is usually 2*maxres. You should just pass the -maxres parameter to hhblits, instead of changing the default value. 

I don't really want to change the default values, since it might break backwards compatibility. It will especially use some more memory.

**Comment by aschafu** [comment]
Hi Milot,
the error with empty alignments which I reported here seems to be unrelated to the maxcol/maxres values. I have seen this in my last run of hhblits against my selfmade pdb_full database. I'll turn this into a separate issue.
Best wishes
    Andrea

**Comment by tamuanand** [comment]
Hi @aschafu @milot-mirdita @martin-steinegger 

I have a related question regarding use of -maxres and -maxcol

> One thing that might be wrong is that maxcol is usually 2*maxres. You should just pass the -maxres parameter to hhblits, instead of changing the default value.

I am trying to build a custom database using HHSuite 3 and I am following the steps [outlined in this wiki](https://github.com/soedinglab/hh-suite/wiki#building-customized-databases)

The issue I am facing: I get segmentation fault and core dump when I do the addss.pl step and this happens when there are long proteins  (say 15k or more amino acids). I have tried passing the command line argument -maxres 32000 and I still get the same segmentation fault error.

Based on @milot-mirdita message about -maxcol being 2*maxres, should I change the src/hhdecl.cpp to reflect this as I do not see a command line option for -maxcol

[I happened to another thread related to maxres issue](https://github.com/soedinglab/hh-suite/issues/67)  and I can see @martin-steinegger noting that 
>sequences longer 20.000 can lead to corrupted memory

_**Please note**_ custom database creation works if I remove the proteins which have more than 15K amino acids.

The question: what workaround should I enable to make sure that custom database creation can work well with longer protein sequences as well.

Thanks in advance,
