### ISSUE TITLE
errors in building customized databases 

### ISSUE THREAD

**Issue by LichAmnesia** [soedinglab/hh-suite#8]
I installed hh-suite and when I want to build customized databases.

`mpirun -np 16 ffindex_apply_mpi bdd_a3m_wo_ss.ff{data,index} -i bdd_hhm.ffindex -d bdd_hhm.ffindex -- hhmake -i stdin -o stdout -v 0`

It returns:
```

- 11:11:15.836 ERROR: Error in /home/fishteam/lich/hh-suite/src/hhfunc.cpp:83: ReadQueryFile:

- 11:11:15.836 ERROR: 	unrecognized input file format in 'stdin'

- 11:11:15.836 ERROR: 	line = Query         A1TKA9
```

I did not use PSIPRED-predicted secondary structure because of the following errors.
`mpirun -np 20 ffindex_apply_mpi bdd_a3m_wo_ss.ff{data,index} -i bdd_a3m.ffindex -d bdd_a3m.ffindex -- addss.pl stdin stdout `

The WARING seems include all the positions in *.a3m.

```
- 11:21:32.381 WARNING: Ignoring invalid symbol '3' at pos. 55 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '=' at pos. 68 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '4' at pos. 69 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '3' at pos. 70 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '%' at pos. 71 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '=' at pos. 84 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '0' at pos. 85 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '9' at pos. 87 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '4' at pos. 88 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

- 11:21:32.381 WARNING: Ignoring invalid symbol '3' at pos. 89 in line 729 of /tmp/O_BQo61Lwq/82t7zubzSx.in.a3m

```

**Comment by meiermark** [comment]
Hello,

I assume you start with a fasta file and start your work with it.
Could you share this fasta file and all commands you used?

Probably:
- ffindex_from_fasta
- hhblits_omp or ffindex_apply_mpi with hhblits

Can you also share your files:
- bdd_a3m_wo_ss.ff{data,index}
- the original fasta-file

Cheers,
Markus

**Comment by jonwells90** [comment]
Hi, 

Not sure if this has already been solved already but I came across this same issue just before going on holiday a couple of weeks ago. I think there might be a couple of typos/errors in the documentation for building custom databases. When building the a3m_wo_ss.ff{index,data} files, I had to deliberately specify the a3m output:

`hhblits_omp -d <path_to/uniprot> -i <db>_fas -oa3m <db>_a3m_wo_ss -n <num_iterations> -cpu <num_threads>`

note the use of `-oa3m`; for me at least, the default -o option produces a .hhr style file, rather than an a3m format file.

Also, I think there's a typo in the documenation detailing the commands for adding the psipred predictions and building hhms? Using LichAmnesia's command as an example:

`mpirun -np 16 ffindex_apply_mpi bdd_a3m_wo_ss.ff{data,index} -i bdd_hhm.ffindex -d bdd_hhm.ffindex -- hhmake -i stdin -o stdout -v 0` 

shouldn't the -d argument be for the .ffdata file? I was able to build a working custom database with these fixes. Just looking at the scripts I used, I see that I also suppressed the output (using `-v 0` again) when adding secondary structure. Can't remember if this was necessary though or not, sorry.

**Comment by meiermark** [comment]
Thanks for your report. Your suggested bugfixes in the userguide should be included now.

**Comment by Icco123** [comment]
When I enter the following command: I get an error:
"ffindex_apply cluster1091_msa.ff{data,index} -i cluster1091_a3m_wo_ss.ffindex -d cluster1091_a3m_wo_ss.ffdata -- hhconsensus -i stdin -M first -maxres 100000 -oa3m stdout"
ERROR:"
Error inhhsuite/hh-suite/src/hhfunc.cpp:84: ReadQueryFile:
unrecognized input file format in 'stdin'
line = 1U09_A.IDs.mfa"
