### ISSUE TITLE
Can't locate HHPaths.pm in @INC

### ISSUE THREAD

**Issue by cokeyk** [soedinglab/hh-suite#81]
I executed the "hhblitsdb.pl" and found a problem: "Can't locate HHPaths.pm in @INC........".  I have check the programs, and add the statement: push{@INC,"....."} , but it doesn't work. Can anyone help me?

**Comment by milot-mirdita** [comment]
`hhblitsdb.pl` is not supported anymore. Most new scripts should not have any issues with `HHPaths.pm` anymore.

**Comment by bognabognabogna** [comment]
Hi, I have the same error when trying to run multithread.pl
I work on MAC OS.
Is there any way to fix it?
Best wishes 


(the command I am trying to run is:
multithread.pl 'my_folder_path/*.fasta' 'hhblits -i $file -d databases/uniclust30_2018_08/uniclust30_2018_08 -o $name.hhr' -cpu 4

**Comment by milot-mirdita** [comment]
Please use `ffindex_build`, `ffindex_apply_mpi`, etc. `multihread.pl` is not supported anymore.

**Comment by bognabognabogna** [comment]
Thank you for your answer! So do I understand well that in order to run hhblits for a number of proteins and get an MSA for each I should follow the guideline below?
When I try it I get the following error from MPI: 'mpirun was unable to find the specified executable file' and it looks like hhblits_mpi cannot be found. Where can I get it from?
Best wishes
 
**### First of all we convert the input FASTA file to a FFindex database with ffindex_from_fasta:
ffindex_from_fasta -s <db>_fas.ff{data,index} <db.fas> 
Now, to build an MSA with HHblits for each sequence in <db>_fas.ff{data,index}, run
mpirun -np <number_threads> \
  hhblits_mpi -i <db>_fas -d <path_to/uniclust30> -oa3m <db>_a3m_wo_ss -n 2 -cpu 1 -v 0**
